### ISSUE TITLE
Possible missing dask[array] and dask_ml requirement for clustering

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [capitalone/global-attribution-mapping#46]
On a fresh install, when importing gam.clustering I get two imports errors, *dask[array]* and *dask_ml*; It might be worth adding them to the requirements.txt

To reproduce:

```bash
conda create -n testing python=3.8 ; conda activate testing ;
python3 -m pip install gam
python3
```
```python3
# inside a py3 shell
# dask[array] error, after being fixed, rerunning gives dask_ml import error.
import gam.clustering  
```

**Comment by rreilly10** [comment]
Thanks for calling this out - we'll have this fixed and a new release published by mid-day tomorrow
